"""comptes lockout brute force

Revision ID: 668f0856f37b
Revises: c38642b6860b
Create Date: 2026-06-29 02:05:08.470842
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "668f0856f37b"
down_revision: str | None = "c38642b6860b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column("accounts", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    op.add_column("accounts", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    # Note : l'index 'readings_recorded_at_idx' est gere par TimescaleDB
    # (create_hypertable). On ne le touche pas.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "last_login_at")
    op.drop_column("accounts", "locked_until")
    op.drop_column("accounts", "failed_login_attempts")
    # ### end Alembic commands ###
