"""compte contact email

Revision ID: 95e5225e5df6
Revises: dca9a09cc778
Create Date: 2026-06-29 05:12:52.736295
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95e5225e5df6"
down_revision: str | None = "dca9a09cc778"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("contact_email", sa.String(length=255), nullable=True))
    # Note : 'readings_recorded_at_idx' est gere par TimescaleDB. On ne le touche pas.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "contact_email")
    # ### end Alembic commands ###
