"""schema initial

Revision ID: c38642b6860b
Revises:
Create Date: 2026-06-29 01:37:31.824528
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c38642b6860b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "COMPANY", name="accountrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="accountstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_accounts_phone_number")),
    )
    op.create_table(
        "audit_log",
        sa.Column("actor_account_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_audit_log_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_account_id"],
            ["accounts.id"],
            name=op.f("fk_audit_log_actor_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_account_id_created_at",
        "audit_log",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sensors",
        sa.Column("hardware_id", sa.String(length=64), nullable=False),
        sa.Column("gateway_ref", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_sensors_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensors")),
        sa.UniqueConstraint("account_id", "hardware_id", name="uq_sensors_account_id_hardware_id"),
    )
    op.create_index("ix_sensors_account_id", "sensors", ["account_id"], unique=False)
    op.create_table(
        "alert_rules",
        sa.Column("sensor_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("GT", "GTE", "LT", "LTE", name="alertcondition", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("threshold", sa.Double(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "CRITICAL",
                "EMERGENCY",
                name="alertseverity",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_alert_rules_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
            name=op.f("fk_alert_rules_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index(
        "ix_alert_rules_account_id_sensor_id",
        "alert_rules",
        ["account_id", "sensor_id"],
        unique=False,
    )
    op.create_table(
        "readings",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_readings_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
            name=op.f("fk_readings_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sensor_id", "recorded_at", name=op.f("pk_readings")),
    )
    op.create_index(
        "ix_readings_account_id_recorded_at",
        "readings",
        ["account_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_readings_account_id_sensor_id_recorded_at",
        "readings",
        ["account_id", "sensor_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("alert_rule_id", sa.Uuid(), nullable=True),
        sa.Column("sensor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "CRITICAL",
                "EMERGENCY",
                name="alertseverity",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ACKNOWLEDGED", "RESOLVED", name="alertstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_alerts_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_alerts_alert_rule_id_alert_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
            name=op.f("fk_alerts_sensor_id_sensors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_account_id_triggered_at", "alerts", ["account_id", "triggered_at"], unique=False
    )
    # ### end Alembic commands ###

    # --- TimescaleDB : hypertable, compression, retention 30 jours -----------
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute(
        "SELECT create_hypertable('readings', by_range('recorded_at'), if_not_exists => TRUE)"
    )
    op.execute(
        "ALTER TABLE readings SET ("
        "timescaledb.compress, "
        "timescaledb.compress_segmentby = 'account_id, sensor_id', "
        "timescaledb.compress_orderby = 'recorded_at DESC')"
    )
    op.execute("SELECT add_compression_policy('readings', INTERVAL '6 hours')")
    op.execute("SELECT add_retention_policy('readings', INTERVAL '30 days')")

    # --- audit_log append-only : trigger bloquant UPDATE / DELETE ------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION el_haress_audit_log_append_only()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log est append-only : UPDATE et DELETE interdits';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION el_haress_audit_log_append_only();
        """
    )

    # --- agregats continus pour le dashboard (groupes par account_id) --------
    # La creation d'un continuous aggregate ne peut pas s'executer dans une
    # transaction : on passe en autocommit pour ce bloc.
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE MATERIALIZED VIEW readings_1min
            WITH (timescaledb.continuous) AS
            SELECT account_id,
                   sensor_id,
                   time_bucket(INTERVAL '1 minute', recorded_at) AS bucket,
                   avg(value) AS avg_value,
                   min(value) AS min_value,
                   max(value) AS max_value
            FROM readings
            GROUP BY account_id, sensor_id, bucket
            WITH NO DATA;
            """
        )
        op.execute(
            """
            CREATE MATERIALIZED VIEW readings_1hour
            WITH (timescaledb.continuous) AS
            SELECT account_id,
                   sensor_id,
                   time_bucket(INTERVAL '1 hour', recorded_at) AS bucket,
                   avg(value) AS avg_value,
                   min(value) AS min_value,
                   max(value) AS max_value
            FROM readings
            GROUP BY account_id, sensor_id, bucket
            WITH NO DATA;
            """
        )
        op.execute(
            "SELECT add_continuous_aggregate_policy('readings_1min', "
            "start_offset => INTERVAL '2 hours', "
            "end_offset => INTERVAL '1 minute', "
            "schedule_interval => INTERVAL '1 minute')"
        )
        op.execute(
            "SELECT add_continuous_aggregate_policy('readings_1hour', "
            "start_offset => INTERVAL '3 days', "
            "end_offset => INTERVAL '1 hour', "
            "schedule_interval => INTERVAL '1 hour')"
        )


def downgrade() -> None:
    # Agregats continus (autocommit, comme la creation).
    with op.get_context().autocommit_block():
        op.execute("DROP MATERIALIZED VIEW IF EXISTS readings_1hour")
        op.execute("DROP MATERIALIZED VIEW IF EXISTS readings_1min")

    # Trigger et fonction append-only de l'audit.
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS el_haress_audit_log_append_only")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alerts_account_id_triggered_at", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_readings_account_id_sensor_id_recorded_at", table_name="readings")
    op.drop_index("ix_readings_account_id_recorded_at", table_name="readings")
    op.drop_table("readings")
    op.drop_index("ix_alert_rules_account_id_sensor_id", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index("ix_sensors_account_id", table_name="sensors")
    op.drop_table("sensors")
    op.drop_index("ix_audit_log_account_id_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("accounts")
    # ### end Alembic commands ###
