"""capteur seuil critique et couleur

Revision ID: d517f8347796
Revises: 95e5225e5df6
Create Date: 2026-06-29 10:34:31.035413
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d517f8347796"
down_revision: str | None = "95e5225e5df6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sensors", sa.Column("critical_threshold", sa.Double(), nullable=True))
    op.add_column("sensors", sa.Column("color", sa.String(length=16), nullable=True))
    # Note : 'readings_recorded_at_idx' est gere par TimescaleDB. On ne le touche pas.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensors", "color")
    op.drop_column("sensors", "critical_threshold")
    # ### end Alembic commands ###
