"""passerelles et rattachement capteurs

Revision ID: dca9a09cc778
Revises: 668f0856f37b
Create Date: 2026-06-29 02:26:51.076395
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca9a09cc778"
down_revision: str | None = "668f0856f37b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateways",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_gateways_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateways")),
    )
    op.create_index("ix_gateways_account_id", "gateways", ["account_id"], unique=False)
    # Note : 'readings_recorded_at_idx' est gere par TimescaleDB. On ne le touche pas.
    op.add_column("sensors", sa.Column("gateway_id", sa.Uuid(), nullable=False))
    op.add_column("sensors", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("sensors", "gateway_ref", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("sensors", "hardware_id", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.drop_constraint(op.f("uq_sensors_account_id_hardware_id"), "sensors", type_="unique")
    op.create_index("ix_sensors_gateway_id", "sensors", ["gateway_id"], unique=False)
    op.create_unique_constraint(
        "uq_sensors_gateway_id_gateway_ref", "sensors", ["gateway_id", "gateway_ref"]
    )
    op.create_foreign_key(
        op.f("fk_sensors_gateway_id_gateways"),
        "sensors",
        "gateways",
        ["gateway_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_sensors_gateway_id_gateways"), "sensors", type_="foreignkey")
    op.drop_constraint("uq_sensors_gateway_id_gateway_ref", "sensors", type_="unique")
    op.drop_index("ix_sensors_gateway_id", table_name="sensors")
    op.create_unique_constraint(
        op.f("uq_sensors_account_id_hardware_id"),
        "sensors",
        ["account_id", "hardware_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("sensors", "hardware_id", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("sensors", "gateway_ref", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.drop_column("sensors", "last_seen_at")
    op.drop_column("sensors", "gateway_id")
    op.drop_index("ix_gateways_account_id", table_name="gateways")
    op.drop_table("gateways")
    # ### end Alembic commands ###
